<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="lizhenzhendeMacBook-Air.local" ignored="1" name="Test Report " tests="4" failures="1" timestamp="07 三月 2023 04:15:07 GMT" time="1.084" errors="0">
  <testcase name="Test01" time="0.0" classname="com.qa.tests.GetTest01"/>
  <testcase name="Test02" time="0.0" classname="com.qa.tests.GetTest01"/>
  <testcase name="Test03" time="0.001" classname="com.qa.tests.GetTest01"/>
  <testcase name="Test04" time="1.017" classname="com.qa.tests.GetTest01">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.qa.tests.GetTest01.Test04() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.qa.tests.GetTest01.Test04() didn't finish within the time-out 1000
]]>
    </failure>
  </testcase> <!-- Test04 -->
  <testcase name="getListUser" time="0.0" classname="com.qa.tests.GetTest01">
    <ignored/>
  </testcase> <!-- getListUser -->
</testsuite> <!-- Test Report  -->
